# Generated by Django 4.2.16 on 2024-10-12 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCodingNexus', '0002_studentlist_userprofile_studentid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birthmonth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birthyear',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
    ]
