# Generated by Django 4.2.16 on 2024-10-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCodingNexus', '0004_userprofile_gender_alter_userprofile_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Instructor', 'Instructor')], max_length=15, null=True),
        ),
    ]
