# Generated by Django 5.1.2 on 2024-11-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCodingNexus', '0008_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='deletion_requested',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
