# Generated by Django 5.1.2 on 2024-11-15 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCodingNexus', '0010_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='course_description',
        ),
    ]
