# Generated by Django 5.1.2 on 2024-11-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCodingNexus', '0011_remove_courses_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='pdf_file',
            field=models.FileField(default='default.pdf', upload_to='pdf_files/'),
        ),
    ]
