# Generated by Django 5.1.2 on 2024-12-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCodingNexus', '0015_fourpicsonewordpuzzle_puzzleattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='invite_token',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
